### ISSUE TITLE
Segmentation fault if extracting jsonv::value that is not as serialization_builder expects

### ISSUE THREAD

**Issue by ajneu** [tgockel/json-voorhees#54] opened 2015-07-20 13:50 UTC
Hi,

just starting to give JSON Voorhees a try...
by trying an example based on the following [link](http://tgockel.github.io/json-voorhees/index.html#serialization_composition).

This following causes a "Segmentation Fault" (64 bit Debian GNU/Linux)

```cpp
#include <iostream>
#include <string>

#include <jsonv/value.hpp>
#include <jsonv/serialization_builder.hpp>
#include <jsonv/parse.hpp>

struct foo
{
  int         a;
  int         b;
  std::string c;
};
struct bar
{
  foo         x;
  foo         y;
  std::string z;
  std::string w;
};

std::ostream& operator<<(std::ostream& os, const foo &f)
{
  os << " a: " << f.a << '\n'
     << " b: " << f.b << '\n'
     << " c: " << f.c << std::endl;
  return os;
}

std::ostream& operator<<(std::ostream& os, const bar &b)
{
  os << "x:\n" << b.x << '\n'
     << "y:\n" << b.y << '\n'
     << "z: " << b.z << '\n'
     << "w: " << b.w << std::endl;
  return os;
}


int main()
{

  jsonv::formats local_formats =
  jsonv::formats_builder()
  .type<foo>()
     .member("a", &foo::a)
     .member("b", &foo::b)
     .default_value(10)
     .member("c", &foo::c)
  .type<bar>()
     .member("x", &bar::x)
     .member("y", &bar::y)
     .member("z", &bar::z)
     .since(jsonv::version(2, 0))
     .member("w", &bar::w)
     .until(jsonv::version(5, 0))
  ;

//      "aaaaa" !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  std::string json_string = R"({
 "x": { "aaaaa": 50, "b": 20, "c": "Blah" }, 
 "y": { "a": 10,          "c": "No B?" },
 "z": "Only serialized in 2.0+",
 "w": "Only serialized before 5.0"
}
)";


  jsonv::formats format = jsonv::formats::compose({ jsonv::formats::defaults(), local_formats });

  jsonv::value val = jsonv::parse(json_string);
  bar x = jsonv::extract<bar>(val, format);
  std::cout << x << std::endl;
  
  return 0;
}
```

I'd expect some kind of exception or error handling here!

The fix is 
```cpp
//      "a" !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
  std::string json_string = R"({
 "x": { "a": 50, "b": 20, "c": "Blah" }, 
 "y": { "a": 10,          "c": "No B?" },
 "z": "Only serialized in 2.0+",
 "w": "Only serialized before 5.0"
}
)";

```

Does this library have exceptions for **parse errors**?
Can I print a nice message to the user explaining:
* line number where error occurred
* expected property (`"a"`) and actual incorrectly supplied property (`"aaaaa"`)

Thanks

**Comment by tgockel** [comment] 2015-07-20 17:19
Oh wow, I can't believe I never tested this one. The issue isn't in *parsing* (the JSON tree is coming out properly), but the serialization reacts really poorly when supplied with extra keys.

To address your two questions at the bottom: By default (when not segfaulting), the serialization system ignores extra keys in the input. That can be fixed with the [`on_extract_extra_keys`](http://tgockel.github.io/json-voorhees/serialization_builder_dsl.html#serialization_builder_dsl_ref_type_level_on_extract_extra_keys) command. With that, you an `std::set` of the extra keys and an `extraction_context`, which allows you to embed the `path` in your exception method (In this case, the `path` would be `.x`, with your extra keys as `{ "aaaaa" }`).

**Closed** 2015-07-25 11:16 UTC
Labels: bug

**Comment by ajneu** [comment] 2015-07-26 17:27
Ahh.... That fix does not work for me.

I am expecting an exception.
Now it just runs happily to the end without throwing an error.

Which error must it throw??

Well it must tell me that it's expecting property `"a"` ([ref](https://github.com/tgockel/json-voorhees/commit/b33f70b78fed1f7d24dd1c20c098babcb48150e3#diff-dbd2472b05ac65582dd5eef39060b77cR290)), but instead getting the wrong property `"aaaaa"`([ref](https://github.com/tgockel/json-voorhees/commit/b33f70b78fed1f7d24dd1c20c098babcb48150e3#diff-dbd2472b05ac65582dd5eef39060b77cR305)).

**Comment by tgockel** [comment] 2015-07-27 01:04
I *think* the issue is that the behavior you're looking for isn't the default -- you have to explicitly turn on the "please do something about extra keys" feature. I added a convenience function called `throw_extra_keys_extraction_error` to help with this.

You can see example usage [here](https://github.com/tgockel/json-voorhees/blob/master/src/jsonv-tests/serialization_builder_tests.cpp#L321).

Let me know if I'm terribly off on this one.

**Comment by ajneu** [comment] 2015-07-27 17:20
Ah yes, thanks!! It's working very nicely now!

(Now if only I could get the line number of errors... Is that currently possible? Thanks)

**Comment by tgockel** [comment] 2015-07-28 02:53
Unfortunately, I do not know of a good way to do that. Check out the big conversions graph:

![JSON Conversions](https://raw.githubusercontent.com/tgockel/json-voorhees/master/doc/conversions.png)

Right now, you can only `extract` from a `jsonv::value` to your custom C++ classes and `value`s do not have information about the source (be it `std::string`, `std::istream` or the DSL). I think I have a pretty decent idea of how I could get line numbers and whatnot into extraction errors, but I haven't fleshed it out completely yet.

As a potential workaround, you *could* use the `tokenizer` directly and build up an `std::map<jsonv::path, parsing_info>` (where `parsing_info` is some tuple of line number and column). Then, you would use that map to look up the `path` from a thrown `jsonv::extraction_error`. Ultimately a major pain, though.
